# OpenSRF / Evergreen Ansible Installer Playbook
# Author: Bill Erickson <berickxx@gmail.com>

- hosts: '{{hosts}}'
  remote_user: '{{deploy_user}}'
  become_method: sudo
  vars_files:
    - settings.yml
  tasks:
  - name: Process OpenSRF Tasks
    include_tasks: opensrf/main.yml
  - name: Process Evergreen Tasks
    include_tasks: evergreen/main.yml
  - name: Process Optional Items
    include_tasks: extras/main.yml
