= Evergreen / OpenSRF Ansible Installer
:author: Bill Erickson, King County Library System
:email: berickxx@gmail.com      

== Note About Virtualized Ejabberd

Ejabberd fails to start in some virtualized invironments (LXD, VirtualBox, 
Google Cloud) due to security constraints baked into its systemd service
configuration.  It's necessary to fix these issues before proceeding with
the installer.

[source,sh]
---------------------------------------------------------------------------
sudo apt install -y ejabberd
sudo vim /lib/systemd/system/ejabberd.service
---------------------------------------------------------------------------

* Change 4 lines to look like this:

[source,conf]
---------------------------------------------------------------------------
PrivateDevices=false
PrivateTmp=false
ProtectHome=false
ProtectSystem=false
---------------------------------------------------------------------------

* Then reload systemctl

[source,sh]
---------------------------------------------------------------------------
sudo systemctl daemon-reload                                                   
sudo systemctl restart ejabberd
---------------------------------------------------------------------------

* Proceed with the install below...

== Quick How-To

Clone and run the Ansible playbook using an Ubuntu login which has sudo
(but not as root).

[source,sh]
---------------------------------------------------------------------------
sudo apt install -y software-properties-common # sometimes necessary
sudo apt update -y
sudo apt install -y git ansible
git clone --branch ubuntu-22.04 https://github.com/berick/evergreen-ansible-installer.git
cd evergreen-ansible-installer
sudo ansible-playbook playbook.yml

# Alternate example demonstrating variable overrides by installing a 
# specific OpenSRF branch.
# sudo ansible-playbook playbook.yml -e osrf_git_branch=rel_3_1

# Install with the sample locales defined in translations.yml
# sudo ansible-playbook playbook.yml -e translations=true

# Install with a different deployment user (named 'deploy') on a remote machine
# sudo ansible-playbook playbook.yml -e hosts=other.example.org -e deploy_user=deploy
---------------------------------------------------------------------------

3. In Chrome/FF navigate to https://<HOSTNAME>/eg/staff/ and click 
   through the SSL warning to access the staff client.

== Settings

Settings are stored in settings.yml.  There are a lot of options.  Please
review these values before installing.  Some items of note:

* load_sample_data: Test data is loaded into the database by default.
* use_nginx: NGINX is installed and used by default

== File Structure

=== playbook.yml 

Main playbook.  It organizes the tasks.

=== settings.yml

Installation settings.  Modify as needed, override via -e var=val
ansible command line option, or store multiple overrides in a file
local_settings.yml and override via -e @local_settings.yml.

=== */main.yml

Entry point for each collection of sub-tasks.

=== extras

Optional packages and configuration not strictly required for OpenSRF 
and Evergreen.
