- name: Install Postgres Prereqs
  apt:
    pkg:
      - python3-psycopg2
    state: present
  become: true
- name: Install Postgres Dependencies
  become: true
  shell: >
    cd {{repo_base}}/Evergreen 
    && PERL_MM_USE_DEFAULT=1 make -f 
    Open-ILS/src/extras/Makefile.install {{pg_install_target}}
- name: Start Postgres
  become: true
  systemd: name=postgresql state=started
- name: Create DB User
  become: true
  become_user: postgres
  postgresql_user: 
    name: "{{database_user}}" 
    password: "{{database_password}}" 
    role_attr_flags: SUPERUSER
- name: Apply EG DB Schema
  # eg_db_config modifies {{eg_install_path}}/conf/ files in 
  # addition to building the schema
  become: true
  become_user: opensrf
  shell: >
    perl {{repo_base}}/Evergreen/Open-ILS/src/support-scripts/eg_db_config 
    {{load_sample_data}} 
    --create-database 
    --create-schema 
    --create-offline 
    --update-config 
    --service all 
    --user {{database_user}} 
    --password {{database_password}} 
    --hostname {{database_host}} 
    --database {{database_database}} 
    --admin-user {{eg_admin_user}} 
    --admin-pass {{eg_admin_pass}}
  when: create_schema | bool
- block:
  - name: Install PGTAP
    become: true
    apt: name=pgtap state=present
  - name: Create PGTAP Extension
    become: true
    become_user: postgres
    postgresql_ext: name=pgtap db={{database_database}}
  when: 
    - create_schema | bool
    - install_pgtap | bool
