- name: Install OpenSRF init script
  become: true
  template: 
    src: extras/service-files/opensrf.init.j2
    dest: /etc/init.d/opensrf 
    owner: root
    group: root
    mode: '0755'
  when: use_service_opensrf | bool
- name: Install OpenSRF Websocketd init script
  become: true
  template:
    src: extras/service-files/websocketd-osrf.init.j2
    dest: /etc/init.d/websocketd-osrf
    owner: root
    group: root
    mode: '0755'
- name: Install Evergreen Reporter init script
  become: true
  template: 
    src: extras/service-files/evergreen-reporter.init.j2
    dest: /etc/init.d/evergreen-reporter 
    owner: root
    group: root
    mode: '0755'
  when: use_service_reporter | bool
- name: Enable OpenSRF service at boot
  become: true
  command: update-rc.d opensrf defaults
  args:
    creates: /etc/rc2.d/S20opensrf
  when: use_service_opensrf | bool
- name: Enable OpenSRF Websocketd service at boot
  become: true
  command: update-rc.d websocketd-osrf defaults
  args:
    creates: /etc/rc2.d/S20websocketd-osrf
- name: Enable Evergreen Reporter service at boot
  become: true
  command: update-rc.d evergreen-reporter defaults
  args:
    creates: /etc/rc2.d/S20evergreen-reporter
  when: use_service_reporter | bool
